---
openapi: 3.0.1
info:
  title: Ecommerce API Documentation
  version: v1
paths:
  "/login":
    post:
      summary: Create a session
      tags:
      - Devise Session
      parameters: []
      responses:
        '200':
          description: devise session created
          headers:
            Authorization:
              type: string
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: test@gmail.com
                    password:
                      type: string
                      default: Test@123
                  required:
                  - email
                  - password
              required:
              - user
          application/xml:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      default: test@gmail.com
                    password:
                      type: string
                      default: Test@123
                  required:
                  - email
                  - password
              required:
              - user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
